version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    entrypoint: sh entrypoint.sh
    working_dir: /home/node
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/home/node
